#pragma once

#ifndef COLOR_BODY_BACKGROUND
#define COLOR_BODY_BACKGROUND "#26262A"
#endif

#ifndef COLOR_FOREGROUND
#define COLOR_FOREGROUND "#999999"
#endif
#ifndef COLOR_LIGHT_FOREGROUND
#define COLOR_LIGHT_FOREGROUND "#505090"
#endif
#ifndef COLOR_ALERT
#define COLOR_ALERT "#105010"
#endif
#ifndef COLOR_BACKGROUND
#define COLOR_BACKGROUND "#111111"
#endif
#ifndef COLOR_LIGHT_BACKGROUND
#define COLOR_LIGHT_BACKGROUND "#CCCCCC"
#endif
#ifndef COLOR_BORDER
#define COLOR_BORDER "#551111"
#endif

#ifndef COLOR_LINK
#define COLOR_LINK "#A07070"
#endif
#ifndef COLOR_LINK_BACKGROUND
#define COLOR_LINK_BACKGROUND "#332222"
#endif
#ifndef COLOR_LINK_SELECTED_BACKGROUND
#define COLOR_LINK_SELECTED_BACKGROUND "#552222"
#endif
#ifndef COLOR_LINK_BORDER
#define COLOR_LINK_BORDER "red"
#endif

#ifndef COLOR_CONTROL
#define COLOR_CONTROL "#aaa"
#endif
#ifndef COLOR_CONTROL_BACKGROUND
#define COLOR_CONTROL_BACKGROUND "#EEEEEE"
#endif
#ifndef COLOR_CONTROL_DISABLED
#define COLOR_CONTROL_DISABLED "#000"
#endif
#ifndef COLOR_CONTROL_SELECTED
#define COLOR_CONTROL_SELECTED "#ccc"
#endif
#ifndef COLOR_CONTROL_UNSELECTED
#define COLOR_CONTROL_UNSELECTED "#aaa"
#endif
#ifndef COLOR_CONTROL_DISABLED_BACKGROUND
#define COLOR_CONTROL_DISABLED_BACKGROUND "#888"
#endif
#ifndef COLOR_CONTROL_BORDER
#define COLOR_CONTROL_BORDER "red"
#endif
#ifndef COLOR_CRITICAL_CONTROL_BACKGROUND
#define COLOR_CRITICAL_CONTROL_BACKGROUND "#dcc"
#endif
#ifndef COLOR_IMPORTANT_CONTROL_BACKGROUND
#define COLOR_IMPORTANT_CONTROL_BACKGROUND "#eec"
#endif
#ifndef COLOR_CRITICAL_CONTROL_BORDER
#define COLOR_CRITICAL_CONTROL_BORDER "#f22"
#endif

#ifndef COLOR_CHART_BACKGROUND
#define COLOR_CHART_BACKGROUND "rgba(192,32,32,0.4)"
#endif
#ifndef COLOR_CHART_CANVAS
#define COLOR_CHART_CANVAS "#EEEEEE"
#endif

#ifndef COLOR_THEME
#define COLOR_THEME "normal"
#endif
#ifndef COLOR_THEMED_INPUT_TEXT
#define COLOR_THEMED_INPUT_TEXT "#000"
#endif
